export enum TipeBahan {
    DAPAT_DIPERGUNAKAN = 'DAPAT DIPERGUNAKAN',
    TERBATAS_DIPERGUNAKAN = 'TERBATAS DIPERGUNAKAN',
    DILARANG = 'DILARANG',
    B3_BARU = 'B3 BARU',
    NON_B3 = 'NON B3',
  }