export enum TipeSurat {
    PERPANJANGAN = 'PERPANJANGAN',
    PENAMBAHAN_KENDARAAN = 'PENAMBAHAN KENDARAAN',
    PENAMBAHAN_JENIS_B3 = 'PENAMBAHAN JENIS B3',
    BARU = 'BARU',
    BARU_IMPORTIR = 'BARU IMPORTIR',
    PRODUSEN = 'PRODUSEN'
}