export enum TipeDokumenPenyimpananB3 {
    PAPAN_NAMA_GUDANG = "Papan Nama Gudang",
    SIRKULASI_UDARA = "Sirkulasi Udara",
    PENGATURAN_SUHU = "Pengaturan Suhu",
    PENERANGAN = "Penerangan",
    LOG_BOOK_CATATAN_STOK = "Log Book/Catatan Stok",
    DINDING = "Dinding",
    LANTAI_KEDAP_AIR = "Lantai Kedap Air",
    KAPASITAS_PENYIMPANAN = "Kapasitas Penyimpanan",
    SALURAN_TUMPAHAN = "Saluran Tumpahan dan Bak Penampungan",
    PENUMPUKAN_B3 = "Penumpukan B3",
    PENEMPATAN_B3 = "Penempatan B3",
    CHECKLIST_PEMERIKSAAN_GUDANG = "Checklist Pemeriksaan Gudang",
    CEKLIS_PEMERIKSAAN_KEMASAN = "Ceklis Pemeriksaan Kemasan",
    KEMASAN_SESUAI_KLASIFIKASI = "Kemasan Sesuai dengan Klasifikasi B3",
    KEMASAN_DENGAN_PALET_RAK = "Kemasan dengan Palet/Rak",
    SIMBOL_LABEL_B3_PADA_KEMASAN = "Simbol dan Label B3 pada Kemasan",
    SOP_BONGKAR_MUAT = "SOP Bongkar Muat/Penanganan B3",
    SOP_TANGGAP_DARURAT = "SOP Tanggap Darurat",
    SOP_PENYIMPANAN = "SOP Penyimpanan",
    SOP_PENANGANAN_KADALUARSA = "SOP Penanganan Barang Kadaluarsa/Offspec/Bekas Kemasan",
    APAR_WATER_SPRINKLE_HYDRAN = "APAR/Water Sprinkle/Hydran",
    EYE_HAND_BODY_WASHER = "Eye/Hand/Body Washer",
    SPILL_KIT = "Spill Kit",
    APD = "APD",
    KOTAK_P3K_KLINIK = "Kotak P3K/Klinik"
  }
  